# Generated by Django 4.2.9 on 2024-02-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
            ],
        ),
    ]
